### ISSUE TITLE
Create port for Genode

### ISSUE THREAD

**Issue by senier** [Componolit/ada-runtime#14]
Create a Genode port that uses a Genode-specific branch of this runtime. Remove duplicate files from Genode. For now, we use the GCC 6.3 runtime source from this repository.

**Comment by jklmnn** [comment]
Can you test the port from https://github.com/jklmnn/genode/commit/5ed15bcc49fe242429e79a318f401d79030e5e5a? If it works you can rebase https://github.com/Componolit/ada-runtime/commit/bbc689fb9a7fb175927eef47d3fae95af3a172c5 onto master. The genode branch would then be for development only as we reference the commit and not the branch in the port anyway.

**Comment by senier** [comment]
The change works in principle. I wonder what the expected outcome of `run/ada_exception` is. Currently this is:

```
[init -> test-ada_exception] Ada exception test
[init -> test-ada_exception] Warning: Get_Jmpbuf_Address_Soft not implemented
[init -> test-ada_exception] Warning: Set_Jmpbuf_Address_Soft not implemented
[init -> test-ada_exception] Error: Exception raised: explicit raise in except.adb: 6
[init -> test-ada_exception] Error: Uncaught exception of type 'Ada::Exception::Program_Error'
[init -> test-ada_exception] Warning: abort called - thread: ep
[init] child "test-ada_exception" exited with exit value 1
^CMakefile:312: recipe for target 'run/ada_exception' failed
```

Then it is stuck until timeout. Shouldn't we be matching for the "Uncought exception" line?

**Comment by jklmnn** [comment]
Yes we should match on the uncaught exception line. I would make this a separate commit as the current behaviour existed before these changes and fixing that is not directly related to this issue.

**Comment by jklmnn** [comment]
Please check https://github.com/jklmnn/genode/commit/dcd94d9d0019c40e9804fbd7cd63d642f0b7548a as a fix for the test.

**Comment by senier** [comment]
Merged to master. The tests work as expected, including the exception test. Thanks!

@jklmnn Please file a pull request to upstream the Genode changes.
