### ISSUE TITLE
Missing Ada.Unchecked_Conversion

### ISSUE THREAD

**Issue by treiher** [Componolit/ada-runtime#2]
Compiling the runtime leads to the following error:

```
gprbuild --RTS=./obj  -Prts
Compile
   [Ada]          ss_utils.adb
ss_utils.ads:2:06: "Ada.Unchecked_Conversion" is not a predefined library unit
ss_utils.ads:2:06: "Ss_Utils (body)" depends on "System.Storage_Elements (body)"
ss_utils.ads:2:06: "System.Storage_Elements (body)" depends on "Ada.Unchecked_Conversion (spec)"
s-stoele.adb:46:10: "Ada" is undefined (more references follow)
s-stoele.adb:46:10: missing "with Ada.Unchecked_Conversion;"
s-stoele.adb:82:54: expected type "System.Storage_Elements.Integer_Address"
s-stoele.adb:82:54: found type "System.Storage_Elements.Storage_Offset"
s-stoele.adb:88:34: expected type "System.Storage_Elements.Integer_Address"
s-stoele.adb:88:34: found type "System.Storage_Elements.Storage_Offset"
s-stoele.adb:98:54: expected type "System.Storage_Elements.Integer_Address"
s-stoele.adb:98:54: found type "System.Storage_Elements.Storage_Offset"
s-stoele.adb:103:14: "To_Offset" is undefined
gprbuild: *** compilation phase failed
make: *** [Makefile:10: obj/adalib/libgnat.a] Error 4
```

@jklmnn do you have an idea how this issue could be solved? I have added my modifications on the sgx-ada branch.

**Comment by jklmnn** [comment]
As we have already discussed I don't really understand how the approach works to build the runtime using gprbuild specifying the target with `--RTS=`.
If I understand the [Documentation](https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/building_with_gprbuild.html#initialization) correctly this only specifies the runtime to be used to build a regular project:

> The invocation of GPRconfig will take into account the target, if specified either by switch –target= on the command line or by attribute Target in the main project. Also, if Ada is one of the languages, it will take into account the Ada runtime directory, specified either by switches –RTS= or –RTS:ada= on the command line or by attribute Runtime (“Ada”) in the main project file. If the Ada runtime is specified as a relative path, gprbuild will try to locate the Ada runtime directory as a subdirectory of the main project directory, or if environment variable GPR_RUNTIME_PATH is defined in the path specified by GPR_RUNTIME_PATH.

On Genode I use `gcc -c -gnatg -gnatp -gnatpg -gnatn2 -I- -I. -I... %.ad(b|s)` to build `*.ali` files from the sources standalone. I tried this in the `src` directory and could build the corresponding ali files here. You only have to make sure to set the correct include paths to all required sources. The ali files should be moved to the `adalib` directory and the specs to `adainclude`. These directories are the standalone runtime (about being standlone, I noticed that the above approach tends to use missing sources from the host systems include paths like /usr/lib... which is probably not what we want). I'd recommend to build the runtime files with the gcc command and put the results manually together. You should then be able to build an ada project using this runtime with `gprbuild --RTS=...` which should not depend on anything else than this runtime. I hope this helps you.

**Comment by senier** [comment]
@treiher: With your newly acquired `make` wizardry skills using plain gcc should not be an issue? Otherwise, comment here if you need ideas ;-)

**Comment by treiher** [comment]
I was able to fix the issue by adding a specification for `Ada.Unchecked_Conversion`, like it was done for muen. So I will use my wizardry skills another time. ;)
