### ISSUE TITLE
Missing context item in binder output

### ISSUE THREAD

**Issue by treiher** [Componolit/ada-runtime#3]
Using the current version of the runtime leads to the following error:

```
Build Libraries
   [gprlib]       ada.lexch
   [bind SAL]     ada
   [Ada]          b__ada.adb
b__ada.adb:61:44: "Parameters" not declared in "System"
gprlib: invocation of /opt/gnat/bin/gcc failed
gprbuild: could not build library for project ada
```

The problem is that `b__ada.ads` does not contain the necessary context item: `with System.Parameters;`. It is not clear to me how `gnatbind` decides which with clauses will be added.

**Comment by jklmnn** [comment]
As discussed in case you really need the dirty solution to insert a custom command after the binder, you could try to define [compilation steps](https://www.adacore.com/gems/gem-157-gprbuild-and-code-generation) (yet I'm not 100% if this is the right approach).

**Comment by senier** [comment]
But I'm 100% sure it's not ;-)

**Comment by treiher** [comment]
Using `No_Run_Time_Mode` solves the issue. At least my sample code works now. But I'm not sure if that is the best solution. Here is a description of `No_Run_Time_Mode` found in the `Rtsfind` specification:

```
   --  For backwards compatibility with previous versions of GNAT, the
   --  compiler recognizes the pragma No_Run_Time. This provides a special
   --  version of configurable run-time mode that operates with the standard
   --  run-time library, but allows only a subset of entities to be
   --  accessed. If any other entity is accessed, then it is treated
   --  as a configurable run-time violation, and the exception
   --  RE_Not_Available is raised.
```

**Comment by treiher** [comment]
The issue is caused by a declaration of `Default_Secondary_Stack_Size : System.Parameters.Size_Type;` which is always added by `gnatbind`. The problem occurs, if no secondary stack (or another feature which refers to `System.Parameters`) is used. We can solve this by adding an specification which always includes `System.Secondary_Stack`.

**Comment by treiher** [comment]
The problem still occurs if a program needs no secondary stack.

**Comment by senier** [comment]
Does that mean compilation fails, even though we always include System.Secondary_Stack?

**Comment by treiher** [comment]
Yes, that is not sufficient.

**Comment by treiher** [comment]
When the original runtime is used, `gnatbind` always sets `Sec_Stack_Used := True` in `ali.adb`. This is caused by the `SS` flag in the P line in `a-exctra.ali` (Ada.Exceptions.Traceback). This seems to be the only ALI file which is always examined by `gnatbinder` and has this flag.

**Comment by treiher** [comment]
Using our runtime `gnatbind` only examines `s-stalib.ali` and `system.ali`. I was able to fix the issue by enforcing the `SS` flag in `s-stalib.ali`. For that purpose I added a dummy function to `s-stalib.ads`: `function Dummy (S : String) return String is (S);`. That is a dirty workaround, but I see no better solution.  @senier @jklmnn Any opinions on that?

**Comment by senier** [comment]
I don't find this workaround too dramatic, as long as it's document properly in the source. Maybe we find out how this is supposed to work one day...
