### ISSUE TITLE
Prove runtime code directly

### ISSUE THREAD

**Issue by senier** [Componolit/ada-runtime#38]
Right now, we cannot prove the runtime directly as gnatprove refuses to prove files that are part of the runtime (i.e. contained also in the runtime used by gnatprove).

We should check whether/how we can run gnatprove on the runtime directly.

**Comment by senier** [comment]
@jklmnn Is this ticket obsolete?

**Comment by jklmnn** [comment]
Yes, it has been fixed with #46.
