### ISSUE TITLE
Muen platform support

### ISSUE THREAD

**Issue by senier** [Componolit/ada-runtime#39]
Implement platform symbols for Muen.

**Comment by jklmnn** [comment]
With https://github.com/Componolit/muen/commit/c174223dfd14e1b574e5708f768cf63b180ef82b and https://github.com/Componolit/ada-runtime/commit/07af7d1ac68d75441f073aaec0e33ce4063bb7b7 Muen can be built completely on our runtime.

**Comment by jklmnn** [comment]
After implementing the CAI log interface I'm aware of what needs to be done to initialize the log channel for the runtime to work. I'll change the runtime in that way using a custom channel called `runtime_log` which is used if available.

**Comment by jklmnn** [comment]
The test in https://github.com/Componolit/ada-runtime/commit/9db85d885d5684edd0de6d3018e78bb874c678a4 also failed with a crashing system. As this doesn't work the runtime will stay as it is.
