### ISSUE TITLE
Remove exception support

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-runtime#41]
If exception support stays, we need to make sure to handle exceptions correctly. I found a good [explanation](https://www.airs.com/blog/archives/464) on how exceptions, the personality function and the `.gcc_except_table` ELF section work together.

**Comment by senier** [comment]
As discussed, we want to remove exception support as it introduces significant complexity with only very minor benefits. To guard preconditions for subprograms called from non-SPARK code, we introduce two no-return functions:

1. `Halt`
2. `Signal_Exception`

The first is guaranteed to halt the component immediately while the second *may or may not* invoke to platform to handle the condition.

**Comment by jklmnn** [comment]
The main problem with exception was the `__gnat_personality_v0` function that introduces somewhat unclear semantics and also caused errors on Genode due to being called with invalid arguments. The main goal of this issue was to remove this function.

After removing all of the exception support, setting all exception restrictions and disabling overflow checks and assertions this function is still required when the secondary stack is used. Removing secondary stack support is no option.

Since the main cause of problems could not be eliminated with the exclusion of exception we opted to keep exception support to at least use its benefits (automatic file and line number information, better integration into environments that also support exceptions, correct semantics for exception cases). The only change is the definition how exceptions work on this runtime. An exception thrown from within SPARK is guaranteed to stop the execution at this point (as it is only thrown when preconditions are not met in SPARK which invalidates all proofs and might lead to undefined behavior). It can be possible that it can be catched and handled by the underlying platform but there is no guarantee. If it cannot be handled the process/application/component that threw the exception will be killed.
