### ISSUE TITLE
Create release and close 1.1 project

### ISSUE THREAD

**Issue by senier** [Componolit/ada-runtime#54]
Create a release from PR #53 and then close this project.

**Comment by jklmnn** [comment]
I also created a Genode commit for the new runtime, could you please review it:
https://github.com/jklmnn/genode/commit/ec1d99ef23a2a9e61d634ed3f48d396d8c05a0ba

**Comment by jklmnn** [comment]
Please also check the release: https://github.com/Componolit/ada-runtime/releases/tag/v1.1.0

**Comment by senier** [comment]
The release notes look good!

**Comment by senier** [comment]
The Genode commit looks OK. Please sort the symbol names to ease future updates.

**Comment by jklmnn** [comment]
The symbols are sorted in https://github.com/jklmnn/genode/commit/3be05e1f9e3525b7904a825db1ce73cd8532d2e9.

**Comment by senier** [comment]
I just realized that we also need to update the [runtime ALIs](https://github.com/Componolit/ada-runtime-alis) and the respective Genode port to match the runtime update.

I wonder, shouldn't we have this discovered in our CI? Do we test Genode's binary packages?

**Comment by jklmnn** [comment]
We only test with `run/test` which worked. Maybe we should test the depot autopilot also.

**Comment by senier** [comment]
Yes, we should do that as broken depots have been a frequent source of trouble on Genode. Cf. #55.

**Comment by jklmnn** [comment]
I tried to update the depot files and updated all paths but it fails to build and cannot find `system.ads` I looked for the include paths but couldn't find out how to set them correctly in the depot tests. We should discuss that with Genode.
