### ISSUE TITLE
Reduce log procedures to a single one

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-runtime#62]
We currently have 3 log procedures for debug, warning and error. Although we only really use this on Genode (which is also the reason why we initially decided this). I think we should reduce that to a single one (or maybe two for info/error). The rationale is that the runtime log is only used for debugging purposes and other mechanisms should be used in the normal application operation. Also error markers and colours could be added by the runtime itself. This would simplify the platform interface.

**Comment by senier** [comment]
Not sure whether we need info/error. Makes sense on Linux, but for debugging a single function should be sufficient.

**Comment by jklmnn** [comment]
Fixed by #63.
