### ISSUE TITLE
Ada.Numerics.Big_Numbers.Big_Integers

### ISSUE THREAD

**Issue by senier** [Componolit/ada-runtime#68]
Future versions of SPARK will retire `Overflow_Mode` / `-gnato??` in favor of `Ada.Numerics.Big_Numbers.Big_Integers` whjich is more flexible.

Unless we plan to execute contracts in the runtime, adding the specification should suffice to use big numbers in contracts.

**Comment by treiher** [comment]
The runtime compatibility tests are currently failing for RecordFlux because of the missing specification. When will they be added to the runtime?

**Comment by senier** [comment]
@jklmnn We'll include that in 1.3 then, please prioritize it.

**Comment by jklmnn** [comment]
Fixed by #77.
