### ISSUE TITLE
Testing exception causes segmentation fault.

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-runtime#8]
I tried to add a test which tests the exception behaviour. The expected behaviour is a call to `ada_raise_exception` which prints the message and exits the program cleanly. Yet this isn't happening. I could track the issue down to `Create_File_Line_String` but not further. When omitting its call in `Rcheck_CE_Explicit_Raise` and issuing a constant message the behaviour above applies.

**Comment by jklmnn** [comment]
I added this test on https://github.com/jklmnn/ada-runtime/tree/issue_8.

**Comment by treiher** [comment]
Could this be related to the secondary stack? Last time we talked about that the current implementation for the POSIX platform which is used for the tests is not correct.

**Comment by jklmnn** [comment]
I first thought it had to do with the `File` argument being a null pointer but the segfault also occured when I passed the address of local string. The secondary stack could indeed be a problem. I'll test that. What bothers me is that the secondary stack test doesn't fail (assuming `ptr[-1]` causes a segfault as well when `ptr` is allocated by malloc).

**Comment by jklmnn** [comment]
https://github.com/jklmnn/ada-runtime/commit/c49ba92336d65fec361081d68d1c9cdffec03e73 indeed seems to fix that behaviour by using the upper bound of the memory region. Could you please check if this solution has any drawbacks, especially if the (indeed quite simple) is correct?

**Comment by treiher** [comment]
I see no drawbacks in the solution.

**Comment by jklmnn** [comment]
Then I'd say you can squash these three commits and put them on master and we can close the issue.

**Comment by treiher** [comment]
The error message looks strange:

```
$ tests/exception/test 
warning: Get_Jmpbuf_Address_Soft not implemented
warning: Set_Jmpbuf_Address_Soft not implemented
Exception raised (256): explicit raise: Sest.adbuf_Address_Soft not implemented
```

**Comment by treiher** [comment]
I found the error in `Create_File_Line_String` and will fix it.

**Comment by senier** [comment]
@treiher: Can you please briefly describe what issue was an how you solved it? That way, our tickets can help us to learn and avoid similar issues in the future.

**Comment by treiher** [comment]
@senier The issue was just a stupid beginner mistake, but as you demand a description: An uninitialized fixed-length string was used to store the exception message. The string was at the same location as the log message which was printed before and so initially contained this message. The file name was just written character-per-character into this string, the rest of the string remained unchanged.

Now the implementation determines the length of the file name before declaring a fixed-length string with the correct size and writing the file name into it.
